SRCS_BROKEN +=  \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_dev.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_busdma.c \

SRCS_UNUSED += \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_core.c

SRCS +=  \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_debug.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_dev.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_device.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_dynamic.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_error.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_fdt_support.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_generic.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_handle_request.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_hid.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_hub_acpi.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_hub.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_lookup.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_mbuf.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_msctest.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_parse.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_pf.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_process.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_request.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_transfer.c \
	$(NXDK_DIR)/lib/bsd_usb/sys/dev/usb/usb_util.c

NXDK_CFLAGS += -I$(NXDK_DIR)/lib/bsd_usb/inc/
NXDK_CFLAGS += -I$(NXDK_DIR)/lib/bsd_usb/sys/
