XBE_TITLE = cubemap
GEN_XISO = $(XBE_TITLE).iso
SRCS = $(CURDIR)/main.cpp
NXDK_DIR = $(CURDIR)/../..
include $(NXDK_DIR)/Makefile

$(CURDIR)/_object.ps.inl: $(CURDIR)/object.ps.asm
	echo "foo"
$(CURDIR)/_environment.ps.inl: $(CURDIR)/environment.ps.asm
	echo "foo"

